version: '3.8'

services:
  oracle-db:
    image: oracleinanutshell/oracle-xe-11g
    container_name: oracle-db
    ports:
      - "1521:1521"
    environment:
      ORACLE_ALLOW_REMOTE: "true"
      ORACLE_DISABLE_ASYNCH_IO: "true"
    volumes:
      - oracle_data:/u01/app/oracle
    restart: unless-stopped

volumes:
  oracle_data:
